### PR TITLE
Script to migrate PSPs to Kubewarden policies.

### LINKED ISSUE #105: Feature Request: provide a migration tool for Pod Security Policies
### Is your feature request related to a problem?

Starting from Kubernetes 1.25, Pod Security Policies are going to be dropped. Users can replace them using Kubewarden policies. However these users would have to learn which Kubewarden policies to use and how to configure them to replicate their current PSPs deployments.

### Solution you'd like

The desired workflow would be to have a user run a script that will:

* Find all the PSPs currently defined inside of a Kubernetes cluster
* Propose Kubewarden Policies to replace them
* When not run in `dry-run`, deploy the Kubewarden Policies into the cluster

The tool should print out yaml files of Kubewarden ClusterAdmissionPolicy objects to be defined.

### Alternatives you've considered

The AppVia folks created [this](https://github.com/appvia/psp-migration) migration tool that does the majority of the work. We would like to offer something more automated, as opposed to copy and paste things into a web UI or [pipe kubectl](https://github.com/appvia/psp-migration#usage) on the cli.

### Anything else?

The desired outcome would be:

* Provide clear instructions about the steps to be performed
* Provide a script (even a bash one) that leverages the [`psp-migration`](https://github.com/appvia/psp-migration) cli
* The script must have a `dry-run` mode that just outputs the resources that would be created inside of the cluster

### PR DESCRIPTION
**Pull request by jvanz**
Adds a simple shell script to migrate the PSPs from a Kubernetes cluster to Kubewarden policies.

Fixes: https://github.com/kubewarden/kubewarden.io/issues/105

### CODE REVIEW

**Review by raulcabello — COMMENTED** [review]
This script is missing some functionality? It looks like it has less options than https://gist.github.com/jvanz/f8ef73739fb4dd555f492e07a8984200 isn't it supposed to be the same script? or am I missing something here?

**Comment by viccuad** [comment]
Agree, I think the PR has an old script version.

**Comment by jvanz** [comment]
No, I've changed it after @flavio's [comment](https://github.com/kubewarden/kubewarden.io/issues/105#issuecomment-1177741164)

**Review by raulcabello — APPROVED** [review]

**Review by viccuad — APPROVED** [review]
Whoops, true! approving!

**Pull request merged**
